### ISSUE TITLE
PET0.ESMF_LogFile should be turned off

### ISSUE THREAD

**Issue by durack1** [CDAT/cdms#106]
@dnadeau4 @doutriaux1 with `2.8.10.rc2-nox` (on ocean) the `PET0.ESMF_LogFile` log file is being written again.. This should be turned off as in the previous releases - it writes out to the current working dir

**Comment by durack1** [comment]
@dnadeau4 this actually makes me wonder whether `ESMPy` is actually in `2.8.10`.. Hang on @doutriaux1 shouldn't this be `2.10.0` not `2.8.10..`?

**Comment by doutriaux1** [comment]
yes 2.10 would be better... tired...

**Comment by durack1** [comment]
@doutriaux1 consider this `rc2` peer review then :smiley:

**Comment by dnadeau4** [comment]
I think I have debug=True somwhere in ESMF.Manager().  I'll check.

**Comment by dnadeau4** [comment]
I turned it off in CDMS, but the tests have it on...

**Comment by doutriaux1** [comment]
@dnadeau4 can you link to the esmf issue you filed please.

**Comment by durack1** [comment]
@dnadeau4 great - looking forward to seeing the next `rc` and checking it all out!
