### ISSUE TITLE
cdms should report more details to anonymous usage sfotware

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdms#123]
at the moment we only report `import cdms`
at: https://github.com/UV-CDAT/cdms/blob/master/Lib/__init__.py#L6

I would like us to send some more detailed info as in genutil for example see:

https://github.com/UV-CDAT/genutil/blob/master/Lib/statistics.py#L705
https://github.com/UV-CDAT/genutil/blob/master/Lib/statistics.py#L747

or

https://github.com/UV-CDAT/cdutil/blob/master/Lib/times.py#L1281
https://github.com/UV-CDAT/cdutil/blob/master/Lib/times.py#L1305

Let me know if that is unclear

**Comment by jypeter** [comment]
What does this do exactly? I confess I select 'no' each time I start a completely new cdat installation and I am prompted for 'anonymous reporting'

- Can this block a script, in case you install a new CDAT and the first time you use cdms is in a script?
- Once you allow the anonymous reporting, will it be called each time you import cdms?
- Can this block a script when you are offline, or running cdms in some secure computing center?

When you ask the user if it's OK to allow reporting, maybe you can display a link (to the web site or github wiki) that the user can read to know what this is about

**Comment by doutriaux1** [comment]
@jypeter we are building the website. No it will not block a script, ever.

**Comment by jypeter** [comment]
OK!

**Comment by dnadeau4** [comment]
What is more details?

**Comment by doutriaux1** [comment]
this is really a cdat_info issue, not a cdms2 issue.
