### ISSUE TITLE
uvcdat conda channel highest cdms2 version is 2.8.1.

### ISSUE THREAD

**Issue by JimBiardCics** [CDAT/cdms#128]
@doutriaux1 @dnadeau4 Is it possible to provide cdms2 2.10 in the conda uvcdat channel?

**Comment by zshaheen** [comment]
@JimBiardCics If you don't want to wait, you can grab any of [these](https://anaconda.org/uvcdat/cdms2/files?version=2017.05.02&channel=nightly). Note that the version number is 2017.05.02 and the label is nightly.
