### ISSUE TITLE
regrid2 vertical regridder seems broken

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdms#15]
see commented out lines in test_regrid2.py

line 98, line 112,

**Comment by dnadeau4** [comment]
That must be it!
https://github.com/UV-CDAT/cdms/blob/master/Test/test_regrid2.py#L98-L111

**Comment by dnadeau4** [comment]
missing_value was set to [1] in tvariable by default
  *  fill_value = numpy.ma.default_fill_value(1.0).astype(dtype)
https://github.com/UV-CDAT/cdms/blob/master/Lib/tvariable.py#L286

Assert that fill_value is set depending of dtype
``` python
        if dtype is None and data is not None:
            dtype = numpy.array(data).dtype
        if fill_value is not None:
            fill_value = numpy.array(fill_value).astype(dtype)
        else:
            fill_value = numpy.ma.MaskedArray(1).astype(dtype).item()
            fill_value = numpy.ma.default_fill_value(fill_value)
```

**Comment by doutriaux1** [comment]
@dnadeau4 the PR is closed but not merged. Re-opening until this is clarified.

**Comment by dnadeau4** [comment]
This was fill value issue that I fixed.   The comment I used `fix` closed the issue automatically.

**Comment by dnadeau4** [comment]
This must be fixed and merged at this time.  They are no more commented lines in test_regrid2.py
