### ISSUE TITLE
python 3 remaining fail tests

### ISSUE THREAD

**Issue by dnadeau4** [CDAT/cdms#165]
- [x] tests/test_forecast_io.py
- [x]  tests/test_cdms_flake8.py
- [x] tests/test_cdscan.py
- [x] tests/test_regrid2.py 
- [x] tests/test_curvilinear_grid.py
- [x] tests/test_EsmfLevelAndTime.py (toVisit issue)
- [x] tests/test_EsmfRegridMpi.py (ESMF C issue) 
- [x] tests/test_dataset_filemap.py
- [x] tests/test_fillvalue.py
- [x] tests/test_allMIPs.py
- [x] tests/test_gemma.py
- [x] tests/test_Esmf3DSmallNative.py
- [x] tests/test_Esmf_3x4_6x8_Bilinear_Masked.py
- [x] tests/test_Esmf_3x4_6x8_Bilinear.py
- [x] tests/test_all_formats.py
- [x] tests/test_periodicity.py
- [x]  tests/test_Esmf3DSmallesmf.py
- [x] tests/test_genericGrid2.py
- [x] tests/test_EsmfSalinity.py
- [x] tests/test_cdms_infile_unlimited_dimension_alter.py
- [x] tests/test_Esmf.py
- [x] tests/test_cdmsfile_rw.py
- [x] tests/test_Esmf_3x4_6x8_Conserve.py
- [x] tests/test_Esmf_3x4_6x8_Conserve_Masked.py

**Comment by doutriaux1** [comment]
The end is near! (in a good way!)

**Comment by doutriaux1** [comment]
@dnadeau4 then we need to merge master in.

**Comment by doutriaux1** [comment]
and test with numpy 1.13 (but separate PR probably for this one, although all tests now pass in master with numpy 1.13)

**Comment by dnadeau4** [comment]
All working for py2 and py3,  osx not ready due to ESMF missing for MAC.
