### ISSUE TITLE
esmf can't be link on OSX

### ISSUE THREAD

**Issue by dnadeau4** [CDAT/cdms#169]
https://github.com/conda-forge/mpich-feedstock/issues/14

**Comment by dnadeau4** [comment]
mpich is now fix and working, but I can't make ESMF compile with OSX due to rpath.

**Comment by doutriaux1** [comment]
@dnadeau4 where is the recipe I can try as well on my side.

**Comment by dnadeau4** [comment]
git clone git@github.com:NESII/esmf-feedstock.git
