### ISSUE TITLE
missing_value attribute in file not respected when reading in

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdms#18]
test_tvariable.py line 50

**Comment by dnadeau4** [comment]
Where is test_tvariable.py?  I cannot find it.

**Comment by doutriaux1** [comment]
hum... not sure...

**Comment by dnadeau4** [comment]
It seems that when we create a variable with subRegion, the missing_value is reset to 1.e20

``` python
(Pdb) v.subRegion((366., 731., 'ccn'), (-42., 42., 'ccn'), (90., 270.)).getMissing()
1e+20
(Pdb) v.getMissing()
-99.9

```

**Comment by dnadeau4** [comment]
BTW, this is a new test created by @chaosphere2112  the file is here:
https://github.com/UV-CDAT/cdms/blob/master/Test/test_tvariable.py
