### ISSUE TITLE
nigthly not triggering anymore on circleci...

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdms#182]
see:
https://circleci.com/gh/UV-CDAT/cdms/376?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

It prints `RESULTS: 0` but does not start the nightly build!

@dnadeau4 any idea why?

**Comment by dnadeau4** [comment]
It only create a build when the branch is "master"
```
circleci_mac.sh:
if [ $RESULT -eq 0 -a $CIRCLE_BRANCH == "master" ]; then bash ./ci-support/conda_upload.sh ; fi
````

**Comment by dnadeau4** [comment]
fixed.
