### ISSUE TITLE
mac python 3 seems broken

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdms#184]
see: https://github.com/UV-CDAT/cdms/pull/183

The original circleci was requesting emsf/esmpy which would somehow force python back down to 27.

I can reproduce the issue on my mac

**Comment by dnadeau4** [comment]
I look at it and I don't understand.  It is taking esmf from my channel on the MAC and Linux for Python3.
```
conda install -n py3 -c nadeau1 esmf esmpy
my esmf is no longer working?
  - esmf -> mpich
  - esmf -> netcdf-fortran 4.4.*
  - esmpy -> esmf ==7.1.0.dev34 -> mpich
  - esmpy -> esmf ==7.1.0.dev34 -> netcdf-fortran 4.4.*
```

**Comment by doutriaux1** [comment]
look at the line above
```
# Create Python 3 environment
cmd="conda create -n py3 -c uvcdat/label/nightly -c conda-forge -c uvcdat libcf distarray cdtime libcdms cdat_info numpy esmf esmpy libdrs_f pyopenssl nose requests flake8 myproxyclient"
```

you were bringing in esmf/esmpy and that was forcing to downgrade python to version 2

**Comment by dnadeau4** [comment]
a8eeeff7a7696fdd067404d0e2f8231166ab1c3b
