### ISSUE TITLE
Unicode strings for axis names

### ISSUE THREAD

**Issue by James-Crean** [CDAT/cdms#225]
When using a unicode string such as u'latitude' instead of 'latitude', CDMS throws the following error when calling axisMatches in Axis.py :
`CDMSError("Specification not acceptable: <type 'unicode'>, latitude",)`

This looks like it may be a regression, as i see 76a2436098e78e51db8211d6738d60d410e96608 mentions that unicode strings worked at one point.

Related issue with some extra details: https://github.com/UV-CDAT/vcs-js/issues/34

**Comment by dnadeau4** [comment]
@James-Crean this is the conversion to py3.  I guess `basestring` does not accept unicode.   Can you try changing it to `str` in axis .py.  If it work, please submit a PR.

**Comment by dnadeau4** [comment]
@James-Crean are you in py2 or py3? In py2 this works
```python
isinstance(u"", basestring)
True
```

You can try this as well
```python
isinstance("", (u"".__class__, "".__class__))
```

**Comment by James-Crean** [comment]
I am using python 2. `isinstance(u"", basestring)` returns true, but the source uses:

```python
if isinstance(specification, str):
```

The conda install for vCDAT lists the following versions:
```
cdms2                     2.12.2018.02.06.18.32.917cab50063372d0fc67430610309c7c2ef9a695.npy1.13          py27_0    uvcdat/label/nightly
libcdms                   3.0.alpha                     0    conda-forge
```

I can make it use basestring and PR it if you want. (You said this is the conversion to python3 so let me know if there is a different repo or something for python2)

**Comment by dnadeau4** [comment]
@James-Crean make sure it works in python 3 as well.  I am not sure that basestring is available in python3

**Comment by doutriaux1** [comment]
@dnadeau4 you're right there's no basestring in py3 the way to make it work for both 2 and 3:
```python
try:
    basestring
except Exception:
    basestring = str

if isinstance(obj, basestring):
     print("It works")
```

**Comment by dnadeau4** [comment]
@doutriaux1 you will have to do that in every files which make the code cumbersome. 

Why do we pass u'latitude' anyways?

I think this is cleaner. 
```python
isinstance("", (u"".__class__, "".__class__))
```

**Comment by dnadeau4** [comment]
This might work too.

```python
from __future__ import unicode_literals
```

**Comment by doutriaux1** [comment]
because it comes from the web/json files, it's in vcdat. They can work around it of course but it is more and more likely that cdms2 will get objects coming from web/json so we need to get it to work in cdms

**Comment by doutriaux1** [comment]
@dnadeau4 yes that might work as well. It's worth a shot as it's a bit cleaner.

**Comment by dnadeau4** [comment]
In python 3, I found 
```python
from past.builtins import basestring
```

**Comment by doutriaux1** [comment]
@dnadeau4 here is a failing code
```python
import cdms2
import cdat_info

f = cdms2.open(cdat_info.get_sampledata_path()+"/clt.nc")

kargs = {u"latitude":(-20,20)}
s=f("clt")

s2 =s.subRegion(**kargs)
```

**Comment by dnadeau4** [comment]
@doutriaux1 that is now working for me. Try it with tomorrow nightly.  I will create a test.

**Comment by dnadeau4** [comment]
I changed everything to six.string_types in branch `issue#225`.
