### ISSUE TITLE
test_Esmf_3x4_6x8_Conserve_Masked failed on MacOS (py2 & py3)

### ISSUE THREAD

**Issue by muryanto1** [CDAT/cdms#226]
Executing nosetests -s /Users/distiller/project/workspace/test_nightly/cdms/tests/test_Esmf_3x4_6x8_Conserve_Masked.py in /private/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/tmpcf3cmu40
b'.F...'
b'======================================================================'
b'FAIL: test2_3x4_to_5x7_cart (test_Esmf_3x4_6x8_Conserve_Masked.TestESMFRegridderMasked)'
b'----------------------------------------------------------------------'
b'Traceback (most recent call last):'
b'  File "/Users/distiller/project/workspace/test_nightly/cdms/tests/test_Esmf_3x4_6x8_Conserve_Masked.py", line 94, in test2_3x4_to_5x7_cart'
b'    self.assertTrue(cdms2.MV2.is_masked(ESMF5x7[2,2]))'
b'AssertionError: False is not true'
b'----------------------------------------------------------------------'
b'Ran 5 tests in 0.122s'
b'FAILED (failures=1)'

**Comment by dnadeau4** [comment]
@muryanto1 for some reason, this did not fail in circleci when I tested it.  Is it still failing for you?

**Comment by muryanto1** [comment]
Hi Denis, yes, it is still failing.
https://circleci.com/gh/UV-CDAT/uvcdat/231

**Comment by dnadeau4** [comment]
Ok, thanks, I merged my branch so it goes into nightly.  I am not sure why it failed,  I logged on circleci and run `python setup.py install` and it passed.  I think you have an old version of CDMS in the nightly but again the test was there....  Hopefully it will work now.

**Comment by muryanto1** [comment]
I verified that the testcase passed in last night nightly (02/21) run. Thanks!
