### ISSUE TITLE
cdscan hangs in Python 3

### ISSUE THREAD

**Issue by pochedls** [CDAT/cdms#261]
**I'm using Python 3.6 with CDAT8** (on crunchy): 

`conda create -n cdat8 -c conda-forge -c cdat python=3.6 cdat mesalib joblib mysql-connector-python scandir`

**When I try to scan some directories** (for example):

`cdscan -x test.xml /p/css03/cmip5_css01/data/cmip5/output1/NOAA-GFDL/GFDL-CM2p1/historical/mon/atmos/Amon/r3i1p1/v20110601/tas/*.nc`

The scan will finish with `test.xml written` (and I verified that the file is written at that time), but cdscan hangs for 1-2 minutes before exiting. This does not happen using Python 2.

**Comment by dnadeau4** [comment]
@pochedls can you try with this env variable?  It might be related to the threads issue.  
export OMP_NUM_THREADS=1

https://github.com/CDAT/cdms/issues/264

**Comment by dnadeau4** [comment]
@pochedls I ran it and it took 11 seconds...

test.xml written
```
real	0m11.771s
user	0m4.547s
sys	0m10.395s
```

**Comment by pochedls** [comment]
This didn't work, but I am going to try to reinstall my environment for #266. 

>test.xml written
>
> real	0m54.770s
> user	0m28.439s
> sys	0m11.969s

**Comment by pochedls** [comment]
@dnadeau4 - I just did a clean install:

`conda create -n cdat8_test -c conda-forge -c cdat python=3.6 cdat mesalib ipython`

with these environmental variables: 

> export OMP_NUM_THREADS=1
> export OPENBLAS_NUM_THREADS=1

and get the same issue:
> real	0m47.417s
> user	0m28.071s
> sys	0m12.099s

**Comment by dnadeau4** [comment]
I used label/v80 but got a "cdtime" libnetcdf issue which hope I have resolved.
```
conda create -n cdat8 -c cdat/label/v80 -c conda-forge  python=3.6 cdat mesalib ipython
```

Can you give this a try?

**Comment by pochedls** [comment]
I tried the environment @dnadeau4 recommends (on crunchy), but Python still hangs after the file is written: 

> real	0m52.671s
> user	0m29.148s
> sys	0m10.955s

**Comment by dnadeau4** [comment]
Can you try setting the UVCAT_ANONYMOUS_LOG to FALSE in:
`~/.uvcdat/.anonymouslog`

**Comment by dnadeau4** [comment]
I tried installing `cdms2` only and got 10.5 seconds

`conda create -n cdms3.0.1 -c conda-forge python=3.6 cdms2`
`conda activate cdms3.0.1`

**Comment by pochedls** [comment]
@dnadeau4 - Turning off anonymous logging seemed to do the trick: I got 12s this time.

**Comment by durack1** [comment]
@pochedls @dnadeau4 yep this thread problem is a real issue, we need to figure out the permanent solution and finalize this as part of CDAT/cdat#2213

**Comment by durack1** [comment]
@pochedls great, if this means we have `cdscan` running in Py3 maybe now it's time to migrate across for the xml scans
