### ISSUE TITLE
regrid2 can't find shared library

### ISSUE THREAD

**Issue by pochedls** [CDAT/cdms#266]
I get the following error calling regrid 2 using lat/lon in a rotated pole grid.

> RegridError: ERROR in /export_backup/pochedley1/bin/anaconda2/envs/cdat8/lib/python3.6/site-packages/regrid2/gsRegrid.py: could not find shared library /export_backup/pochedley1/bin/anaconda2/envs/cdat8/lib/python3.6/site-packages/pycf/pylibcf.{so,dylib,dll,DLL}

even though I appear to have the shared library on my path:

`ls /export_backup/pochedley1/bin/anaconda2/envs/cdat8/lib/python3.6/site-packages/pycf/pylibcf.*
/export_backup/pochedley1/bin/anaconda2/envs/cdat8/lib/python3.6/site-packages/pycf/pylibcf.cpython-36m-x86_64-linux-gnu.so*`

The difference appears to be that regrid2 is looking for `pylibcf.so` and I have `pylibcf.cpython-36m-x86_64-linux-gnu.so`. 

Should the library I have work? Or is this representative of a problem when setting up my environment?

**Comment by pochedls** [comment]
I tried linking the library I have to the one regrid2 is looking for: 

`ln -s /export_backup/pochedley1/bin/anaconda2/envs/cdat8/lib/python3.6/site-packages/pycf/pylibcf.cpython-36m-x86_64-linux-gnu.so /export_backup/pochedley1/bin/anaconda2/envs/cdat8/lib/python3.6/site-packages/pycf/pylibcf.so`

but that didn't work: 

> RegridError: ERROR in /export_backup/pochedley1/bin/anaconda2/envs/cdat8/lib/python3.6/site-packages/regrid2/gsRegrid.py: could not open shared library /export_backup/pochedley1/bin/anaconda2/envs/cdat8/lib/python3.6/site-packages/pycf/pylibcf.{so,dylib,dll,DLL}

**Comment by durack1** [comment]
@pochedls thanks for kicking the tires on py3, most of the in-house use is still stuck in py2.

**Comment by dnadeau4** [comment]
That is an installation issue.  Have you used one of these installation yaml file?  
https://github.com/CDAT/cdat/wiki/install

**Comment by dnadeau4** [comment]
@pochedls can you provide me with some code so I can reproduce the error.  I just installed a new cdat8 environment and my tests passed....

**Comment by pochedls** [comment]
@dnadeau4 - I think I used something along the lines of this to create my environment: 

`conda create -n cdat8 -c conda-forge -c cdat python=3.6 cdat mesalib joblib mysql-connector-python scandir`

**Comment by dnadeau4** [comment]
@pochedls I think you want "cdat/label/v80" from what I see in the file, but you line should work. 

Can you provide me with some basic code that I can run to make sure that pylibcf works?  My tests using libcf is working fine.

**Comment by pochedls** [comment]
@dnadeau4 

This relies on some xmls that are available on crunchy/grim: does this give you an error?

```import cdms2

# grab a target grid
fh = cdms2.open('/work/cmip5-dyn/fx/sftlf/cmip5.CCSM4.historical.r0i0p0.fx.atmos.fx.sftlf.000000.1.0.xml')
targetGrid = fh('sftlf').getGrid()
fh.close()

# get data to regrid
f = cdms2.open('/work/cmip5-dyn/rcp85/seaIce/mon/sic/cmip5.bcc-csm1-1-m.rcp85.r1i1p1.mon.seaIce.OImon.sic.000000.v20120715.0.xml')
sic = f('sic', time=('2006-1-1', '2007-1-1'))
f.close()

# regrid
diag = {}
sic_new = sic.regrid(targetGrid, regridTool='esmf', regridMethod = 'linear', missing=-9999, coordSys='deg', diag = diag, periodicity = 1) ```

**Comment by dnadeau4** [comment]
I got good results.
```
sic_new = sic.regrid(targetGrid, regridTool='esmf', regridMethod = 'linear', missing=-9999, coordSys='deg', diag = diag, periodicity = 1)
/export_backup/nadeau1/anaconda52/miniconda3/envs/cdat8/lib/python3.6/site-packages/cdms2/avariable.py:1114: Warning: 
avariable.regrid: regridTool = 'esmf' requires bounds for source grid, will switch to regridTool = 'libcf'
                    
  warnings.warn(message, Warning)
```

**Comment by dnadeau4** [comment]
try to reinstall a new environment...

- wget https://raw.githubusercontent.com/cdat/cdat/master/conda/cdat-v80_py3.Linux.yaml
- conda env create -n cdat8 -f ./cdat-v80_py3.Linux.yaml
- conda activate cdat8

**Comment by pochedls** [comment]
Hi @dnadeau4 - thank you this worked for me. 

Do you think this resulted because I did not use the yaml file? We had a gcc library conflict on crunchy around the time I installed cdat8 that prevented me from compiling some other libraries (fortran libraries using f2py).

**Comment by dnadeau4** [comment]
The new `cdat8`  use `gcc7` and if you use` gcc4.5` code, the dependencies get mixed up especially with fortran code.  I think that is what happened.  `gcc7` creates these extensions `.cpython-36m-x86_64-linux-gnu.so`.  It seems that you had a mix up of compilers for pycf and libcf.

**Comment by pochedls** [comment]
Closing this, because it is working with a fresh environment: 

`conda create -n cdat8 -c conda-forge -c cdat python=3.6 cdat mesalib joblib mysql-connector-python scandir ipython`
