### ISSUE TITLE
tests_all_formats.py and test_cdscan.py are failing in macos_nightly_py2 and py3

### ISSUE THREAD

**Issue by muryanto1** [CDAT/cdms#268]
macos_nightly_py3 -- https://circleci.com/gh/CDAT/cdat/5319
macos_nightly_py2 -- https://circleci.com/gh/CDAT/cdat/5318

b'======================================================================'
b'ERROR: testESGF (test_all_formats.TestFormats)'
b'----------------------------------------------------------------------'
b'Traceback (most recent call last):'
b'  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py3/lib/python3.6/site-packages/cdms2/dataset.py", line 1096, in __init__'
b'    _fileobj_ = Cdunif.CdunifFile(path, mode)'
b'OSError: NetCDF: DAP server error'
b'During handling of the above exception, another exception occurred:'
b'Traceback (most recent call last):'
b'  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py3/lib/python3.6/site-packages/cdms2/dataset.py", line 398, in openDataset'
b'    file = CdmsFile(uri, mode)'
b'  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py3/lib/python3.6/site-packages/cdms2/dataset.py", line 1098, in __init__'
b"    raise CDMSError('Cannot open file %s (%s)' % (path, err))"
b'cdms2.error.CDMSError: Cannot open file https://aims3.llnl.gov/thredds/dodsC/cmip5_css01_data/cmip5/output1/BCC/bcc-csm1-1-m/1pctCO2/day/ocean/day/r1i1p1/v20120910/tos/tos_day_bcc-csm1-1-m_1pctCO2_r1i1p1_02800101-02891231.nc (NetCDF: DAP server error)'
b'During handling of the above exception, another exception occurred:'
b'Traceback (most recent call last):'
b'  File "/Users/distiller/project/workdir/cdms/tests/test_all_formats.py", line 49, in testESGF'
b'    f = cdms2.open("https://aims3.llnl.gov/thredds/dodsC/cmip5_css01_data/cmip5/output1/BCC/bcc-csm1-1-m/1pctCO2/day/ocean/day/r1i1p1/v20120910/tos/tos_day_bcc-csm1-1-m_1pctCO2_r1i1p1_02800101-02891231.nc")'
b'  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py3/lib/python3.6/site-packages/cdms2/dataset.py", line 405, in openDataset'
b'    raise CDMSError(msg)'
b'cdms2.error.CDMSError: Error in DODS open of: https://aims3.llnl.gov/thredds/dodsC/cmip5_css01_data/cmip5/output1/BCC/bcc-csm1-1-m/1pctCO2/day/ocean/day/r1i1p1/v20120910/tos/tos_day_bcc-csm1-1-m_1pctCO2_r1i1p1_02800101-02891231.nc'
b'You have a .dodsrc in your HOME directory, try to remove it'
b'----------------------------------------------------------------------'

==> and I am able to access https://aims3.llnl.gov/esg-orp/home.htm?redirect=https%3A%2F%2Faims3.llnl.gov%2Fthredds%2FdodsC%2Fcmip5_css01_data%2Fcmip5%2Foutput1%2FBCC%2Fbcc-csm1-1-m%2F1pctCO2%2Fday%2Focean%2Fday%2Fr1i1p1%2Fv20120910%2Ftos%2Ftos_day_bcc-csm1-1-m_1pctCO2_r1i1p1_02800101-02891231.nc.dds

------
b'.ncopen: filename "https://dataserver.nccs.nasa.gov/thredds/dodsC/bypass/CREATE-IP/Reanalysis/NASA-GMAO/GEOS-5/MERRA/mon/atmos/zg.ncml": NetCDF: DAP server error'
b'E'
b'======================================================================'
b'ERROR: retrieve value from cdscan'
b'----------------------------------------------------------------------'
b'Traceback (most recent call last):'
b'  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py3/lib/python3.6/site-packages/cdms2/dataset.py", line 1096, in __init__'
b'    _fileobj_ = Cdunif.CdunifFile(path, mode)'
b'OSError: NetCDF: DAP server error'
b'During handling of the above exception, another exception occurred:'
b'Traceback (most recent call last):'
b'  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py3/lib/python3.6/site-packages/cdms2/dataset.py", line 398, in openDataset'
b'    file = CdmsFile(uri, mode)'
b'  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py3/lib/python3.6/site-packages/cdms2/dataset.py", line 1098, in __init__'
b"    raise CDMSError('Cannot open file %s (%s)' % (path, err))"
b'cdms2.error.CDMSError: Cannot open file https://dataserver.nccs.nasa.gov/thredds/dodsC/bypass/CREATE-IP/Reanalysis/NASA-GMAO/GEOS-5/MERRA/mon/atmos/zg.ncml (NetCDF: DAP server error)'
b'During handling of the above exception, another exception occurred:'
b'Traceback (most recent call last):'
b'  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py3/lib/python3.6/site-packages/cdms2/cdscan.py", line 1072, in main'
b'    f = cdms2.open(path)'
b'  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py3/lib/python3.6/site-packages/cdms2/dataset.py", line 405, in openDataset'
b'    raise CDMSError(msg)'
b'cdms2.error.CDMSError: Error in DODS open of: https://dataserver.nccs.nasa.gov/thredds/dodsC/bypass/CREATE-IP/Reanalysis/NASA-GMAO/GEOS-5/MERRA/mon/atmos/zg.ncml'
b'You have a .dodsrc in your HOME directory, try to remove it'
b'During handling of the above exception, another exception occurred:'
b'Traceback (most recent call last):'
b'  File "/Users/distiller/project/workdir/cdms/tests/test_cdscan.py", line 63, in testopenFile'
b'    cdscan(argv)'
b'  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py3/lib/python3.6/site-packages/cdms2/cdscan.py", line 1075, in main'
b"    raise RuntimeError('Error opening file ' + path)"
b'RuntimeError: Error opening file https://dataserver.nccs.nasa.gov/thredds/dodsC/bypass/CREATE-IP/Reanalysis/NASA-GMAO/GEOS-5/MERRA/mon/atmos/zg.ncml'

**Comment by dnadeau4** [comment]
@muryanto1 
It seems to me that you are using the `curl` from OSX and not the one from `conda-forge`.
`conda-forge` does not use the keychain and a PKCS12 Certficate, only OSX, you  need to use the `conda-forge` curl which is compiled differently than the on which comes with OSX by default.

```
* TCP_NODELAY set
* Connected to aims3.llnl.gov (198.128.245.183) port 443 (#0)
* WARNING: SSL: CURLOPT_SSLKEY is ignored by Secure Transport. The private key must be in the Keychain.
* WARNING: SSL: Certificate type not set, assuming PKCS#12 format.
```

**Comment by dnadeau4** [comment]
@muryanto1 Note,  the certificate cannot be found in the directory.
```
CMD: ls -al /Users/distiller/.esg
total 16
drwxr-xr-x   3 distiller  staff   102 Aug 19 20:29 .
drwxr-xr-x+ 37 distiller  staff  1258 Aug 19 20:29 ..
```

**Comment by muryanto1** [comment]
Thanks Denis. Sorry for the mistake. I will fix it to pick up the right curl when I return then.

**Comment by muryanto1** [comment]
Tests are passing in nightlies. Closing this bug.
