### ISSUE TITLE
test_all_formats.py and test_cdscan.py failed with install from v80 channel

### ISSUE THREAD

**Issue by muryanto1** [CDAT/cdms#269]
`2 cdms testcases are failing when ran with install from v80 channels
for MacOS and Linux (both py2 and py3)
For ex: 
Install: linux_cdat_v80_channel_py2 -- https://circleci.com/gh/CDAT/cdat/5544

  conda create -n cdat_v80_channel_py2 -c conda-forge -c cdat/label/v80 python=2.7 cdat
  source activate cdat_v80_channel_py2
  conda install -c conda-forge -c cdat -c pcmdi/label/nightly -c pcmdi nose coverage image-compare pcmdi_metrics cia easydev nbsphinx mesalib; source deactivate
  source deactivate

Details:
+ tests/test_all_formats.py
======================================================================
ERROR: testDAP (test_all_formats.TestFormats)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/workdir/cdms/tests/test_all_formats.py", line 24, in testDAP
    f = cdms2.open('http://test.opendap.org/opendap/hyrax/data/nc/coads_climatology.nc')
  File "/home/circleci/project/workdir/miniconda/envs/cdat_v80_channel_py2/lib/python2.7/site-packages/cdms2/dataset.py", line 405, in openDataset
    raise CDMSError(msg)
CDMSError: Error in DODS open of: http://test.opendap.org/opendap/hyrax/data/nc/coads_climatology.nc

+ tests/test_cdscan.py
.ncopen: filename "https://dataserver.nccs.nasa.gov/thredds/dodsC/bypass/CREATE-IP/Reanalysis/NASA-GMAO/GEOS-5/MERRA/mon/atmos/zg.ncml": NetCDF: DAP server error
E
======================================================================
ERROR: retrieve value from cdscan
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/workdir/cdms/tests/test_cdscan.py", line 58, in testopenFile
    cdscan(argv)
  File "/home/circleci/project/workdir/miniconda/envs/cdat_v80_channel_py2/lib/python2.7/site-packages/cdms2/cdscan.py", line 1075, in main
    raise RuntimeError('Error opening file ' + path)
RuntimeError: Error opening file https://dataserver.nccs.nasa.gov/thredds/dodsC/bypass/CREATE-IP/Reanalysis/NASA-GMAO/GEOS-5/MERRA/mon/atmos/zg.ncml`

**Comment by dnadeau4** [comment]
@muryanto1 can you rerun v80 for cdms2.  I think it was a `http` glitch.

**Comment by muryanto1** [comment]
It is still failing daily.
linux_cdat_v80_channel_py2 - https://circleci.com/gh/CDAT/cdat/5635
linux_cdat_v80_channel_py3 - https://circleci.com/gh/CDAT/cdat/5634
macos_cdat_v80_channel_py2 - https://circleci.com/gh/CDAT/cdat/5632
macos_cdat_v80_channel_py3 - https://circleci.com/gh/CDAT/cdat/5638

**Comment by dnadeau4** [comment]
This is now fix for nightly.  Can you check if it works for v80?

**Comment by dnadeau4** [comment]
I pushed a new tag v3.0.1 which fix the failure due to ".dodsrc" left over.  That file is only needed to access "ESGF" and will make other "OpeNDAP" request fail if not deleted due to authentication.  This is the way "libcurl" works.

**Comment by dnadeau4** [comment]
@muryanto1 if it pass can you close?

**Comment by muryanto1** [comment]
tests failed in nightly now.
