### ISSUE TITLE
var.getTime().getBounds() returns None for a timeseries file

### ISSUE THREAD

**Issue by chengzhuzhang** [CDAT/cdms#286]
I did get following warning. although not apply to T axis

filename = 'sst_187001_201612.nc'
fin = cdms2.open(filename)
var = fin('sst')
/export_2/zhang40/anaconda2/envs/acme_diags_env/lib/python2.7/site-packages/cdms2/axis.py:1618: UserWarning: 
Your first bounds[0,0] -180.000000000000000 will be corrected to -180.000000000000000
Your bounds bounds[-1,1] 180.000000000000000 will be corrected to 180.000000000000000
  warnings.warn(msg, UserWarning)

Header of the file as follows:
netcdf sst_187001_201612 {
dimensions:
	time = UNLIMITED ; // (1764 currently)
	longitude = 360 ;
	latitude = 180 ;
	nv = 2 ;
variables:
	float time(time) ;
		time:standard_name = "time" ;
		time:long_name = "Time" ;
		time:units = "days since 1870-1-1 0:0:0" ;
		time:calendar = "gregorian" ;
		time:axis = "T" ;
		time:bounds = "time_bnds" ;
	float longitude(longitude) ;
		longitude:standard_name = "longitude" ;
		longitude:long_name = "Longitude" ;
		longitude:units = "degrees_east" ;
		longitude:axis = "X" ;
	float latitude(latitude) ;
		latitude:standard_name = "latitude" ;
		latitude:long_name = "Latitude" ;
		latitude:units = "degrees_north" ;
		latitude:axis = "Y" ;
	float time_bnds(time, nv) ;
	float sst(time, latitude, longitude) ;
		sst:standard_name = "sea_surface_temperature" ;
		sst:long_name = "sst" ;
		sst:units = "C" ;
		sst:_FillValue = -1.e+30f ;
		sst:missing_value = -1.e+30f ;
		sst:cell_methods = "time: lat: lon: mean" ;

**Comment by chengzhuzhang** [comment]
As discussed with @dnadeau4 , It turns out that the original data used have non-monotonic Time bounds. It would be useful to throw an error in this case.

**Comment by doutriaux1** [comment]
@chengzhuzhang I don't think it matters. You probably just didn't generate bounds for the time axis. You can use cdtime to generate bounds or simply try: `var.getTime().setBounds(None)` to generate automagic bounds.

**Comment by chengzhuzhang** [comment]
@doutriaux1 Thank you for the comment! I'm pretty sure that the time bounds is there. I put the data on acme1 (also accessible from aims4). I did find the time_bnds is non-monotonic though. var.getTime().setBounds(None) seems not working. I still need to look into how to use cdtime...

**Comment by chengzhuzhang** [comment]
@dnadeau4  and @doutriaux1 helped to fixed the data problem. 
Firstly, bounds = 'time_bnds' needs to be included as an attr in time
secondly, cdutil.SetTimeBoundsMonthly can easily generate correct mounthly time bounds
