### ISSUE TITLE
Slicing with a range larger than what's available in the file doesn't give an error.

### ISSUE THREAD

**Issue by zshaheen** [CDAT/cdms#288]
Given a file `PRECC_000101_000512.nc`, when we slice from `(0, 144)` (for years `0001` to `0012`), it gives the same values as slicing from `(0, 60)` (for when the years are `0001` to `0005`).

We should probably have a way to throw an error when this occurs.

**Comment by zshaheen** [comment]
Also, when the user gives a strange index range (ex: `(-23736, -23676)`), CDMS still doesn't throw an error.

**Comment by dnadeau4** [comment]
@zshaheen can you write an example?

**Comment by dnadeau4** [comment]
@zshaheen can you try it again?

**Comment by dnadeau4** [comment]
This is what we did last week right?

**Comment by zshaheen** [comment]
@dnadeau4, this is not what we did last week. This is specifically giving strange values to the `time` argument in `var = f('PRECT', time=slice(start, end))`. Attached is a sample data file and script, detailing what I'm talking about. The test was ran on cdms2 "3.0.0" (which is 3.1.0 I believe) on macOS.


[cdms_issues_288.zip](https://github.com/CDAT/cdms/files/2954785/cdms_issues_288.zip)

**Comment by zshaheen** [comment]
@dnadeau4, what we did last week was to see why for some data the variable isn't gotten. As you remember, it seems to *not* be a cdms issue, it seems to be on our end.

**Comment by dnadeau4** [comment]
@zshaheen I think the behavior of your script is right.  CDMS2 must truncate your negative to the smallest array index and truncate the larger index to the array length.

**Comment by zshaheen** [comment]
@dnadeau4, sure if that's correct then we can close this issue. Issuing a warning might be needed maybe. If the user tries to slice 1 year or 10 years, but gets only 1 year due to the data, warning them would be nice.

**Comment by dnadeau4** [comment]
@doutriaux1 Do you think we need a warning for this issue in CDMS?

**Comment by zshaheen** [comment]
This seems like an issue of garbage in, garbage out. If you pass in garbage parameters, you should expect garbage output. And as @dnadeau4 said, most people don't pass in the slices.

**Comment by dnadeau4** [comment]
@zshaheen can we close this then?

**Comment by zshaheen** [comment]
@zshaheen Yep, since like you said, most users just slice by the years by passing in a string, not an integer index. We'll probably be doing this as well from now on.
