### ISSUE TITLE
cdms2.createVariable have missing value 1 by default

### ISSUE THREAD

**Issue by chengzhuzhang** [CDAT/cdms#295]
When using cdms2.createVariable to create a variable. When missing_value is not defined, it returns 1.

**Comment by doutriaux1** [comment]
@chengzhuzhang can you copy/paste a small example? Thx!

**Comment by dnadeau4** [comment]
@doutriaux1 I was with @chengzhuzhang and this line is problematic
https://github.com/CDAT/cdms/blob/master/Lib/tvariable.py#L315

It might have been fix and maybe she is using a old version.   The next line should work
https://github.com/CDAT/cdms/blob/master/Lib/tvariable.py#L316

@chengzhuzhang can you tell me what cdms version you are using?
```
conda list | grep cdms
```

**Comment by chengzhuzhang** [comment]
Good catch! this is on an institutional machine. And the cdat version is 2.6..
