### ISSUE TITLE
Inconsistency between fill value of cdms transient variable and asms

### ISSUE THREAD

**Issue by chengzhuzhang** [CDAT/cdms#299]
**Describe the bug**
When I use cdms to open the Hadley center sst data, with fill value/ missing value = -1e+30. There is inconsistency between fill value of cdms transient variable and asms

**Data needed To Reproduce**
```
import cdms2
import cdutil
import MV2
#Data downloaded from here https://www.metoffice.gov.uk/hadobs/hadisst/data/download.html
#This script is to fix overlapping timebounds from original data
#also add ice mask

# Set nc classic as outputs
cdms2.setCompressionWarnings(0) ; # Suppress warnings
cdms2.setNetcdfShuffleFlag(0)
cdms2.setNetcdfDeflateFlag(1) ; # was 0 130717
cdms2.setNetcdfDeflateLevelFlag(9) ; # was 0 130717
cdms2.setAutoBounds(1) ; # Ensure bounds on time and depth axes are generated

filepath = '/p/user_pub/e3sm/zhang40/analysis_data_e3sm_diags/HadISST/original_data/'
filename1 = 'HadISST_ice.nc'
filename2 = 'HadISST_sst.nc'
fin1 = cdms2.open(filepath +filename1)
fin2 = cdms2.open(filepath +filename2)
ice = fin1('sic')
sst = fin2('sst')

sst_masked = MV2.masked_where(ice>0,sst,copy=True)
sst_masked.id = 'sst'


```

**Comment by doutriaux1** [comment]
`sst_masked` is a new transient variable. Hence it makes sense that the new fill_value is 1.e20. It's the default fill_value for an MV. You also made a copy it;s a brand new array. The value of fill_value is irelevent anyway unless to convert to pure numpy. And even then you shuold probably specifying the fill_value to use when you go from masked to filled.

**Comment by dnadeau4** [comment]
This gives me the same result than cdms2.  So it is a `numpy` issue. 
```
numpy.ma.masked_where(ice.asma()>0,sst.asma(), copy=True)
```

Actually since the data is already masked, the fill_value is not used here.  It will only be used if you call sst_masked.filled() and then all the `mask==True` indices will be replaced by the filled_value.
In  this case you should make sure the the resulting `fill_value` has the same value as the original `fill_value`

```python

# this position is mask in the original array and the resulting array.
>>> sst[0,6,143]
masked_array(data = --,
             mask = True,
       fill_value = 1e+20)

>>> sst_masked[0,6,143]
masked_array(data = --,
             mask = True,
       fill_value = 1e+20)

# lets look at the value under the mask (we have the original fill_value)
>>> sst[0,6,143].data
array(-1.0000000150474662e+30, dtype=float32)
>>> sst_masked[0,6,143].data
array(-1.0000000150474662e+30, dtype=float32)

# make sure we copy the original fill_value for further operations if needed.
>>> sst_masked.fill_value=sst.fill_value
>>> sst_masked.fill_value
-1e+30
```
