### ISSUE TITLE
nighlty breaks pmp

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdms#310]
https://896-10345204-gh.circle-artifacts.com/0/tests_html/test_pmp_basic_test_parameters_file.html

**Comment by doutriaux1** [comment]
Actually this is using v81 label. So it's cdms from conda-forge.

**Comment by doutriaux1** [comment]
@dnadeau4 ok the "good" news is that the bug does not come from a cdms change but from a change in my `pmp` branch. So not critical. The bad news is that it might still be a bug...

**Comment by dnadeau4** [comment]
@doutriaux1 when you get more details let me know and I will look into it.

**Comment by doutriaux1** [comment]
@dnadeau4 I think it was coming from a change in pmp. Master passes now.
