### ISSUE TITLE
Doc: remove "VCS Quick Reference (Cheat Sheet)" from cdms2 documentation ?

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdms#323]
I have just found out that there is a version of _VCS Quick Reference (Cheat Sheet)_ in  [9. APPENDIX B](https://cdms.readthedocs.io/en/latest/manual/cdms_appendix.html#appendix-b) of **cdms2** documentation!

That's probably not the most logical place to store it 

@doutriaux1 this nice pdf (even if some parts may be out of date) should be in the **vcs** documentation, or could be used as a model for updating [VCS Quick Reference](https://cdat-vcs.readthedocs.io/en/latest/quick-reference.html?highlight=VCS%20Quick%20Reference#vcs-quick-reference)

**Comment by dnadeau4** [comment]
It used to be there int he original CDMS.  I updated the CDMS quick reference, but VCS is @doutriaux1 .  We can move it, or remove it.

**Comment by jypeter** [comment]
I think it's confusing to leave such a reference to vcs there, now that you are trying to make the original cdat components more independent from each other

On the other hand, I don't really know what to do with the [5. Plotting CDMS data in Python](https://cdms.readthedocs.io/en/latest/manual/cdms_5.html#plotting-cdms-data-in-python) section, that relies on both vcs and cdms2. I guess it can stay in cdms, if you think you can keep it up-to-date if vcs keywords change later, or this kind of changes. Or maybe it would make more sense to put this in a notebook, and reference this notebook in a new cdms manual section dedicated to examples

While you decide what to do with [5. Plotting CDMS data in Python](https://cdms.readthedocs.io/en/latest/manual/cdms_5.html#plotting-cdms-data-in-python), you should definitely add an explicit link from this section to the [vcs documentation](https://cdat-vcs.readthedocs.io/en/latest/#vcs-visualization-control-system)

**Comment by doutriaux1** [comment]
@jypeter I agree, `cdms2` and `vcs` are now separate pkg. We should remove this section (after scanning it to see what could be ported back to vcs)

**Comment by dnadeau4** [comment]
I removed the Chapter 5 and deleted the cheat sheet from the CDMS documentation.
