### ISSUE TITLE
CDMS2 axis.getBounds() returns wrong leading and trailing bounds for monotonic decreasing axis

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/cdms#34]
I have a data set with a polar stereographic grid. The y axis has 448 elements and is monotonic decreasing from 5837500.0 m to -5337500.0 m. When the getBounds method is called it produces a leading edge bound of (90.0, 90.0) and a trailing edge bound of (-90.0, -90.0). One of the files from the data set is attached.

[sample.zip](https://github.com/UV-CDAT/uvcdat/files/506948/sample.zip)

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/2129

**Comment by JimBiardCics** [comment]
@dnadeau4 We can continue the discussion here.

**Comment by doutriaux1** [comment]
@JimBiardCics should the following be a latitude axis?
```python
	float ygrid(ygrid) ;
		ygrid:valid_range = -5350000.f, 5850000.f ;
		ygrid:units = "meters" ;
		ygrid:long_name = "projection_grid_y_centers" ;
		ygrid:standard_name = "projection_y_coordinate" ;
		ygrid:axis = "Y" ;
```
as in `ygrid.isLatitude()` return `True`

**Comment by JimBiardCics** [comment]
@doutriaux1 It is a Y axis in a polar stereographic projection centered on the north pole. It is not a latitude axis as far as I'm concerned.

**Comment by doutriaux1** [comment]
@JimBiardCics ok, it's not the root of the problem but I'm wondering if `axis=Y` should really mean `latitude` in cdms. @dnadeau4 what do you think? Should we also check units or grid type? Or is it considered a latitude by CF conventions? Poking @taylor13 @durack1 @painter1 here to get feedback. Probably should eventually move this to a new issue though.

**Comment by doutriaux1** [comment]
@JimBiardCics fixed take a look at #131 should make it in 2.10 (will updatethe tag point or create 2.10.1)

**Comment by taylor13** [comment]
In CF, axis=Y does not only apply to latitude.  It applies to the axis considered by the user to normally be plotted as the ordinate (vertical axis).  It can be used as a guide by software when plotting x-y plots.  So, I think CDMS/UVCDAT should probably only use this attribute when plotting.

Here's what CF says:

>  Coordinate types other than latitude, longitude, vertical, and time are allowed. To identify generic spatial coordinates we recommend that the axis attribute be attached to these coordinates and given one of the values X, Y or Z. The values X and Y for the axis attribute should be used to identify horizontal coordinate variables. If both X- and Y-axis are identified, X-Y-up should define a right-handed coordinate system, i.e. rotation from the positive X direction to the positive Y direction is anticlockwise if viewed from above. We strongly recommend that coordinate variables be used for all coordinate types whenever they are applicable. 

Furthermore to determine if a coordinate is latitude, you should check the units:

> Hence, determination that a coordinate is a latitude type should be done via a string match between the given unit and one of the acceptable forms of degrees_north.  Optionally, the latitude type may be indicated additionally by providing the standard_name attribute with the value latitude, and/or the axis attribute with the value Y.

**Comment by JimBiardCics** [comment]
That seems to have fixed the problem. Thanks!
