### ISSUE TITLE
Problems with udunits in CDAT82

### ISSUE THREAD

**Issue by durack1** [CDAT/cdms#374]
I have just encountered the following issue while trying to load `vcs`

```python
import vcs
~anaconda3/envs/cdat82MesaPy3/lib/python3.7/site-packages/unidata/__init__.py:2: UserWarning: unidata package is deprecated please use genutil.udunits instead of unidata.udunits
  warnings.warn("unidata package is deprecated please use genutil.udunits instead of unidata.udunits")
```

Might be something quick to fix before 8.2 is officially released

@downiec @jasonb5 @muryanto1

**Comment by jasonb5** [comment]
@durack1 thanks for the report, looks like @muryanto1 has fixed this https://github.com/CDAT/vcsaddons/pull/45. Will be in the CDAT 8.2.1 release.

**Comment by durack1** [comment]
@jasonb5 perfect, looking forward to seeing this land!
