### ISSUE TITLE
Make mpi4py initialization optional

### ISSUE THREAD

**Issue by jasonb5** [CDAT/cdms#425]
Currently CDMS2 has two states; with and without mpi4py (dependent on whether mpi4py package is available). 

Here we'll propose a change to add an environment variable that will prevent mpi4py initializing when the mpi4py package is available.

Proposed environment variable: CDMS_NO_MPI

**Comment by jypeter** [comment]
Sounds reasonable. This has reminded me of 2 months of discussion with Charles exactly **8 years** ago, in the **not good** old times when you had to compile CDAT. The whole thing started with my sending this mail
```
Argh, f__k!

I thought I was almost there because I got
[ 71%] Completed 'CDAT'
[ 72%] Built target CDAT

but I can't import cdms2 because mpi4py is missing [...]
```

Is the usage of `mpi4py` by cdms explained in a tutorial somewhere, or is it just something that takes place under the hood, without the user needing to know about it?
