### ISSUE TITLE
cdsm2 createGenericGrid need to be generic

### ISSUE THREAD

**Issue by dnadeau4** [CDAT/cdms#5]
_From @doutriaux1 on August 9, 2016 16:18_

``` python
f2=  cdms2.open(fnmcurv)
In [4]: s=f2("sample")
In [5]: g=s.getGrid()
In [6]: lat = g.getLatitude()
In [7]: lon=g.getLongitude()
In [9]: g2 = cdms2.createGenericGrid(lat,lon)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-da081e424d79> in <module>()
----> 1 g2 = cdms2.createGenericGrid(lat,lon)
```

_Copied from original issue: UV-CDAT/uvcdat#2081_

**Comment by dnadeau4** [comment]
_From @doutriaux1 on August 9, 2016 16:20_

Out[10]: '/home/doutriaux1/miniconda2/envs/Test/share/uvcdat/sample_data/sampleCurveGrid4.nc'

**Comment by dnadeau4** [comment]
@doutriaux1 please revise pull request #119

**Comment by durack1** [comment]
@dnadeau4 while you're looking at grids the UV-CDAT/uvcdat#1707 and #42 should also get a look

**Comment by doutriaux1** [comment]
@dnadeau4 please refrain to close before PR is in. Thanks.
