### ISSUE TITLE
can't delete file attribute

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/cdms#50]
``` python
import cdms2
f=cdms2.open("attribute.nc","w")
f.my_Att = "Anything"
del(f.my_Att)'
```

gives us

```
Segmentation fault (core dumped)
```

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/1398

**Comment by doutriaux1** [comment]
might be already fixed

**Comment by doutriaux1** [comment]
we should just add a test if not in already

**Comment by dnadeau4** [comment]
https://github.com/UV-CDAT/cdms/blob/master/tests/test_regressions.py#L41
