### ISSUE TITLE
Building/testing modifies source tree

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/cdms#52]
The following files are created in the source tree when building/testing UVCDAT:

```
installation/install.py
testing/cdms2/junk.xml
testing/dv3d/.baseline_path
```

I'm not sure what the purpose of the first two are, but the third contains a path to the baseline directory for the `dv3d` tests. I had added a mechanism to properly pass that path into `dv3d` via an argument[1], but it appears @ThomasMaxwell reverted my change at some point. This should be cleaned up -- Source clutter with build-dependent info will cause issues when multiple builds reference the same source tree.

[1] https://github.com/UV-CDAT/uvcdat/commit/65d545aa97895ed71fd98027ccd43cf905077318#diff-d3e8161439180f671ad7a70585da5cc3

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/1364

**Comment by dnadeau4** [comment]
@doutriaux1 This is more a vcs issue.  The cdsm2 file `junk.xml` is being deleted.
