### ISSUE TITLE
Update numpy to 1.10

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/cdms#59]
They've just released a bugfix update to the 1.9.x branch: http://docs.scipy.org/doc/numpy/release.html

I'll update the sources and issue an pull request when I deal with the other issues #856, #847, #846 (which is going to need some testing), and #841 and #814 

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/885

**Comment by durack1** [comment]
@dnadeau4 this is close-able I believe
Fix UV-CDAT/uvcdat#885
