### ISSUE TITLE
from . import git broken ?

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdms#85]
On crunchy using master:

```python
/export/doutriaux1/miniconda2/envs/2017.1.30/lib/python2.7/site-packages/cdms2/__init__.py in <module>()
      5 import cdat_info
      6 cdat_info.pingPCMDIdb("cdat", "cdms2")
----> 7 from . import git
      8 from . import myproxy_logon
      9 

ImportError: cannot import name git

```

**Comment by dnadeau4** [comment]
@doutriaux1 can we close this?

**Comment by victorquik** [comment]
Hi I am having this problem when trying to use the cdms2 library


---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-c5c5017ad4ac> in <module>()
----> 1 import cdms2 as cdm

/home/vestella/anaconda2/lib/python2.7/site-packages/cdms2/__init__.py in <module>()
      5 import cdat_info
      6 cdat_info.pingPCMDIdb("cdat", "cdms2")  # noqa
----> 7 from . import git  # noqa
      8 from . import myproxy_logon  # noqa
      9 

ImportError: cannot import name git

Any idea what I am doing wrong installing the package?


I am using the following : 

conda list
 packages in environment at /home/vestella/anaconda2:

 Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py27h08a7f0c_0
alabaster                 0.7.10           py27he5a193a_0
anaconda                  custom           py27h4a00acb_0
anaconda-client           1.6.9                    py27_0
anaconda-navigator        1.6.8            py27h2ea4365_0
anaconda-project          0.8.2            py27h236b58a_0
argparse                  1.4.0                     <pip>
asn1crypto                0.24.0                   py27_0
astroid                   1.6.1                    py27_0
astropy                   2.0.3            py27h14c3975_0
attrs                     17.4.0                   py27_0
babel                     2.5.3                    py27_0
backports                 1.0              py27h63c9359_1
backports.functools_lru_cache 1.4              py27he8db605_1
backports.shutil_get_terminal_size 1.0.0            py27h5bc021e_2
backports_abc             0.5              py27h7b3c97b_0
basemap                   1.1.0                    py27_3    conda-forge
beautifulsoup4            4.6.0            py27h3f86ba9_1
biggus                    0.15.0                   py27_0    conda-forge
bitarray                  0.8.1            py27h14c3975_1
bkcharts                  0.2              py27h241ae91_0
blaze                     0.11.3           py27h5f341da_0
bleach                    2.1.2                    py27_0
bokeh                     0.12.13          py27h5233db4_0
boto                      2.48.0           py27h9556ac2_1
bottleneck                1.2.1            py27h21b16a3_0
bzip2                     1.0.6                h9a117a8_4
ca-certificates           2018.03.07                    0
cairo                     1.14.12              h77bcde2_0
cartopy                   0.15.1           py27h29bd39c_5
cdat_info                 8.0                      py27_0    conda-forge
cdecimal                  2.3              py27h14c3975_3
cdms2                     3.0.1            py27h6091dcd_1    conda-forge
cdtime                    3.0              py27h6091dcd_1    conda-forge
certifi                   2018.8.24                py27_1
cf-plot                   2.1.57           py27he47850c_0    ncas
cf-python                 2.0.6                         0    ncas
cf_units                  1.1.3                    py27_1    conda-forge
cffi                      1.11.4           py27h9745a5d_0
chardet                   3.0.4            py27hfa10054_1
clapack                   3.2.1                h470a237_1    conda-forge
click                     6.7              py27h4225b90_0
click-plugins             1.0.3                     <pip>
cligj                     0.4.0                     <pip>
cloudpickle               0.5.2                    py27_1
clyent                    1.2.2            py27h7276e6c_1
cmocean                   1.1                        py_0    conda-forge
colorama                  0.3.9            py27h5cde069_0
conda                     4.5.11                   py27_0
conda-build               3.0.23           py27h7bd6724_0
conda-env                 2.6.0                         0    conda-forge
conda-verify              2.0.0            py27hf052a9d_0
configparser              3.5.0            py27h5117587_0
contextlib2               0.5.5            py27hbf4c468_0
cryptography              2.1.4            py27h6697b16_0
curl                      7.58.0               h84994c4_0
cycler                    0.10.0           py27hc7354d3_0
cython                    0.27.3           py27hc56b35e_0
cytoolz                   0.9.0            py27h14c3975_0
dask                      0.16.1                   py27_0
dask-core                 0.16.1                   py27_0
datashape                 0.5.4            py27hf507385_0
dbus                      1.12.2               hc3f9b76_1
decorator                 4.2.1                    py27_0
descartes                 1.1.0                     <pip>
dill                      0.2.7.1                   <pip>
distarray                 2.12.2                   py27_0    conda-forge
distributed               1.20.2                   py27_0
docutils                  0.14             py27hae222c1_0
easyesn                   0.1.4.5                   <pip>
ecmwf_grib                1.23.1                        0    conda-forge
entrypoints               0.2.3            py27h502b47d_2
enum34                    1.1.6            py27h99a27e9_1
eofs                      1.3.0                    py27_0    conda-forge
esmf                      7.1.0r                        0    conda-forge
esmpy                     7.1.0r                   py27_1    conda-forge
et_xmlfile                1.0.1            py27h75840f5_0
expat                     2.2.5                he0dffb1_0
fastcache                 1.0.2            py27h14c3975_2
filelock                  2.0.13           py27h61a9c69_0
Fiona                     1.7.10.post1              <pip>
flask                     0.12.2           py27h6d5c1cd_0
flask-cors                3.0.3            py27h1a8a27f_0
fontconfig                2.12.4               h88586e7_1
freetype                  2.8                  hab7d2ae_1
funcsigs                  1.0.2            py27h83f16ab_0
functools32               3.2.3.2          py27h4ead58f_1
future                    0.16.0                   py27_2    conda-forge
futures                   3.2.0            py27h7b459c0_0
g2clib                    1.6.0                         5    conda-forge
geopandas                 0.3.0                     <pip>
geos                      3.6.2                         1    conda-forge
get_terminal_size         1.0.0                haa9412d_0
gevent                    1.2.2            py27h475ea6a_0
gitdb2                    2.0.4                     <pip>
GitPython                 2.1.11                    <pip>
glib                      2.53.6               h5d9569c_2
glob2                     0.6              py27hcea9cbd_0
gmp                       6.1.2                h6c8ec71_1
gmpy2                     2.0.8            py27h4cf3fa8_2
graphite2                 1.3.10               hf63cedd_1
greenlet                  0.4.12           py27hac09c53_0
grin                      1.2.1                    py27_4
gst-plugins-base          1.12.4               h33fb286_0
gstreamer                 1.12.4               hb53b477_0
h5py                      2.7.1            py27h2697762_0
harfbuzz                  1.7.4                hc5b324e_0
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1               h9caa474_1
heapdict                  1.0.0                    py27_2
html5lib                  1.0.1            py27h5233db4_0
icu                       58.2                 h9c2bf20_1
idna                      2.6              py27h5722d68_1
imageio                   2.2.0            py27hf108a7f_0
imagesize                 0.7.1            py27hd17bf80_0
intel-openmp              2018.0.0             hc7b2577_8
ipaddress                 1.0.19                   py27_0
ipykernel                 4.8.0                    py27_0
ipython                   5.4.1                    py27_2
ipython_genutils          0.2.0            py27h89fb69b_0
ipywidgets                7.1.1                    py27_0
iris                      1.13.0                   py27_1    conda-forge
iris-grib                 0.10.1                   py27_0    conda-forge
isort                     4.2.15           py27hcfa4749_0
itsdangerous              0.24             py27hb8295c1_1
jasper                    1.900.1                       4    conda-forge
jbig                      2.1                  hdba287a_0
jdcal                     1.3              py27h2cc5433_0
jedi                      0.11.1                   py27_0
jinja2                    2.10             py27h4114e70_0
jpeg                      9b                   h024ee3a_2
jsonschema                2.6.0            py27h7ed5aa4_0
jupyter                   1.0.0                    py27_4
jupyter_client            5.2.2                    py27_0
jupyter_console           5.2.0            py27hc6bee7e_1
jupyter_core              4.4.0            py27h345911c_0
jupyterlab                0.31.5                   py27_0
jupyterlab_launcher       0.10.2                   py27_0
lapack                    3.6.1                         1    conda-forge
lazy-object-proxy         1.3.1            py27h682c727_0
libcdms                   3.0.1                         0    conda-forge
libcf                     1.0.1                    py27_1    conda-forge
libcurl                   7.58.0               h1ad7b7a_0
libdrs                    3.0                           0    conda-forge
libdrs_f                  3.0.1                h2cd7f18_3    conda-forge
libedit                   3.1                  heed3624_0
libffi                    3.2.1                hd88cf55_4
libgcc                    7.2.0                h69d50b8_2
libgcc-ng                 7.2.0                h7cc24e2_2
libgfortran               3.0.0                         1
libgfortran-ng            7.2.0                h9f7466a_2
libmo_unpack              3.0                           1    conda-forge
libnetcdf                 4.4.1.1              h816af47_8
libopenblas               0.2.20               h9ac9557_7
libpng                    1.6.34               hb9fc6fc_0
libsodium                 1.0.15               hf101ebd_0
libssh2                   1.8.0                h9cfc8f7_4
libstdcxx-ng              7.2.0                h7a57d05_2
libtiff                   4.0.9                h28f6b97_0
libtool                   2.4.6                h544aabb_3
libxcb                    1.12                 hcd93eb1_4
libxml2                   2.9.7                h26e45fe_0
libxslt                   1.1.32               h1312cb7_0
llvmlite                  0.21.0           py27h6dad3f9_0
locket                    0.2.0            py27h73929a2_1
lxml                      4.1.1            py27hf71bdeb_1
lzo                       2.10                 h49e0be7_2
markupsafe                1.0              py27h97b2822_1
matplotlib                2.1.2            py27h0e671d2_0
mccabe                    0.6.1            py27h0e7c7be_1
mesalib                   17.3.9               hdd5ec5b_0    conda-forge
mistune                   0.8.3                    py27_0
mkl                       2018.0.1             h19d6760_4
mkl-service               1.1.2            py27hb2d42c5_4
mo_pack                   0.2.0                    py27_1    conda-forge
mpc                       1.0.3                hec55b23_5
mpfr                      3.1.5                h11a74b3_2
mpich                     3.2                           5    conda-forge
mpmath                    1.0.0            py27h9669132_2
msgpack-python            0.5.1            py27h6bb024c_0
multipledispatch          0.4.9            py27h9b5f95a_0
multiprocess              0.70.5                    <pip>
munch                     2.2.0                     <pip>
navigator-updater         0.1.0            py27h0f9cd39_0
nbconvert                 5.3.1            py27he041f76_0
nbformat                  4.4.0            py27hed7f2b2_0
nc_time_axis              1.0.2                    py27_0    conda-forge
ncurses                   6.0                  h9df7e31_2
netcdf-fortran            4.4.4                         6    conda-forge
netcdf4                   1.3.1                    py27_1    conda-forge
networkx                  2.1                      py27_0
nltk                      3.2.5            py27hec5f4de_0
nose                      1.3.7            py27heec2199_2
notebook                  5.4.0                    py27_0
numba                     0.36.2          np114py27he2868da_0
numexpr                   2.6.4            py27hd318778_0
numpy                     1.14.3           py27h28100ab_1
numpy-base                1.14.3           py27h0ea5e3f_1
numpydoc                  0.7.0            py27h9647a75_0
odo                       0.5.1            py27h9170de3_0
olefile                   0.45.1                   py27_0
openpyxl                  2.4.10                   py27_0
openssl                   1.0.2p               h14c3975_0
ossuuid                   1.6.2                hfc679d8_0    conda-forge
owslib                    0.15.0                     py_0    conda-forge
packaging                 16.8             py27h5e07c7c_1
pandas                    0.22.0           py27hf484d3e_0
pandoc                    1.19.2.1             hea2e7c5_1
pandocfilters             1.4.2            py27h428e1e5_1
pango                     1.41.0               hd475d92_0
parso                     0.1.1            py27h718acc2_0
partd                     0.3.8            py27h4e55004_0
patchelf                  0.9                  hf79760b_2
path.py                   10.5             py27hefe4bee_0
pathlib                   1.0.1                    py27_0
pathlib2                  2.3.0            py27h6e9d198_0
patsy                     0.5.0                    py27_0
pcmdi-metrics-1.1.2-6     g9a0d4e8                  <pip>
pcre                      8.41                 hc27e229_1
pep8                      1.7.1                    py27_0
pexpect                   4.3.1                    py27_0
pickleshare               0.7.4            py27h09770e1_0
pillow                    5.0.0            py27h3deb7b8_0
pip                       9.0.1            py27ha730c48_4
pip                       18.0                      <pip>
pixman                    0.34.0               hceecf20_3
pkginfo                   1.4.1            py27hee1a9ad_1
pluggy                    0.6.0            py27h1f4f128_0
ply                       3.10             py27hd6d9ae5_0
progressbar2              3.37.1                    <pip>
proj4                     4.9.3                         5    conda-forge
prompt_toolkit            1.0.15           py27h1b593e1_0
psutil                    5.4.3            py27h14c3975_0
ptyprocess                0.5.2            py27h4ccb14c_0
py                        1.5.2            py27h203d672_0
pycairo                   1.15.4           py27h1b9232e_1
pycodestyle               2.3.1            py27h904819d_0
pycosat                   0.6.3            py27ha4109ae_0
pycparser                 2.18             py27hefa08c5_1
pycrypto                  2.6.1            py27h14c3975_7
pycurl                    7.43.0.1         py27hb7f436b_0
pyepsg                    0.3.2                    py27_0    conda-forge
pyflakes                  1.6.0            py27h904a57d_0
PyGithub                  1.43                      <pip>
pygments                  2.2.0            py27h4a8b6f5_0
PyJWT                     1.6.4                     <pip>
pyke                      1.1.1                    py27_0    conda-forge
pylint                    1.8.2                    py27_0
pyodbc                    4.0.22           py27hf484d3e_0
pyopenssl                 17.5.0           py27hcee3be0_0
pyparsing                 2.2.0            py27hf1513f8_1
pyproj                    1.9.5.1                  py27_0    conda-forge
pyqt                      5.6.0            py27h4b1e83c_5
pyshp                     1.2.12                     py_0    conda-forge
pysocks                   1.6.7            py27he2db6d2_1
pytables                  3.4.2            py27h1f7bffc_2
pytest                    3.3.2                    py27_0
python                    2.7.14              h1571d57_29
python-dateutil           2.6.1            py27h4ca5741_1
python-ecmwf_grib         1.23.1                   py27_0    conda-forge
python-utils              2.3.0                     <pip>
pytz                      2017.3           py27h001bace_0
pywavelets                0.5.2            py27hecda097_0
pyyaml                    3.12             py27h2d70dd7_1
pyzmq                     16.0.3           py27hc579512_0
qt                        5.6.2               h974d657_12
qtawesome                 0.4.4            py27hd7914c3_0
qtconsole                 4.3.1            py27hc444b0d_0
qtpy                      1.3.1            py27h63d3751_0
readline                  7.0                  ha6073c6_4
regionmask                0.3.1                     <pip>
requests                  2.18.4           py27hc5b0589_1
rope                      0.10.7           py27hfe459b0_0
ruamel_yaml               0.15.35          py27h14c3975_1
scandir                   1.6              py27hf7388dc_0
scikit-image              0.13.1           py27h14c3975_1
scikit-learn              0.19.1           py27h445a80a_0
scipy                     1.0.0            py27hf5f0f52_0
seaborn                   0.8.1            py27h633ea1e_0
seawater                  3.3.4                     <pip>
send2trash                1.4.2                    py27_0
setuptools                38.4.0                   py27_0
shapely                   1.6.2                    py27_1    conda-forge
simplegeneric             0.8.1                    py27_2
singledispatch            3.4.0.3          py27h9bcb476_0
sip                       4.18.1           py27he9ba0ab_2
six                       1.11.0           py27h5f960f1_1
sklearn                   0.0                       <pip>
smmap2                    2.0.4                     <pip>
snowballstemmer           1.2.1            py27h44e2768_0
sortedcollections         0.5.3            py27h135218e_0
sortedcontainers          1.5.9                    py27_0
sphinx                    1.6.6                    py27_0
sphinxcontrib             1.0              py27h1512b58_1
sphinxcontrib-websupport  1.0.1            py27hf906f22_1
spyder                    3.2.6                    py27_0
sqlalchemy                1.2.1            py27h14c3975_0
sqlite                    3.22.0               h1bed415_0
ssl_match_hostname        3.5.0.1          py27h4ec10b9_2
statsmodels               0.8.0            py27hc87d62d_0
subprocess32              3.2.7            py27h373dbce_0
sympy                     1.1.1            py27hc28188a_0
tblib                     1.3.2            py27h51fe5ba_0
terminado                 0.8.1                    py27_1
testpath                  0.3.1            py27hc38d2c4_0
tk                        8.6.7                hc745277_3
toolz                     0.9.0                    py27_0
tornado                   4.5.3                    py27_0
traitlets                 4.3.2            py27hd6ce930_0
typing                    3.6.2            py27h66f49e2_0
udunits2                  2.2.25                        1    conda-forge
unicodecsv                0.14.1           py27h5062da9_0
unixodbc                  2.3.4                hc36303a_1
urllib3                   1.22             py27ha55213b_0
wcwidth                   0.1.7            py27h9e3e1ab_0
webencodings              0.5.1            py27hff10b21_1
werkzeug                  0.14.1                   py27_0
wheel                     0.30.0           py27h2bc6bb2_1
widgetsnbextension        3.1.0                    py27_0
wrapt                     1.10.11          py27h04f6869_0
xarray                    0.10.0           py27hd0a7aca_0
xlrd                      1.1.0            py27ha77178f_1
xlsxwriter                1.0.2            py27h12cbc6b_0
xlwt                      1.3.0            py27h3d85d97_0
xz                        5.2.3                h55aa19d_2
yaml                      0.1.7                had09818_2
zeromq                    4.2.2                hbedb6e5_2
zict                      0.1.3            py27h12c336c_0
zlib                      1.2.11               ha838bed_2

**Comment by doutriaux1** [comment]
I had not seen this error in a long time. Please try to update cdat_info to the nightly version (or reinstall it) it might help. Either way please let me know.
```
conda update -c cdat/label/nightly -c conda-forge -c cdat cdat_info
```

Thx for the conda env info. I will try to reproduce your error on my end as well

**Comment by victorquik** [comment]
Hi again, 

I updated but got this error: 

1 import cdms2 as cdm

/home/vestella/anaconda2/lib/python2.7/site-packages/cdms2/__init__.py in <module>()
     18 
     19 # CDMS datatypes
---> 20 from .cdmsobj import CdArray, CdChar, CdByte, CdDouble, CdFloat, CdFromObject, CdInt, CdLong, CdScalar, CdShort, CdString  # noqa
     21 
     22 # Functions which operate on all objects or groups of objects

/home/vestella/anaconda2/lib/python2.7/site-packages/cdms2/cdmsobj.py in <module>()
      3 """
      4 
----> 5 from . import cdmsNode
      6 import cdtime
      7 import glob

/home/vestella/anaconda2/lib/python2.7/site-packages/cdms2/cdmsNode.py in <module>()
      8 from numpy import get_printoptions, set_printoptions, inf
      9 from . import CDML
---> 10 import cdtime
     11 import re
     12 import string

ImportError: libnetcdf.so.13: cannot open shared object file: No such file or directory

I updated the netcdf library early, so no idea why there is a problem.

**Comment by doutriaux1** [comment]
my bad, it brought in only part of newer built librarie, please try to update all:

```
conda update -c cdat/label/nightly -c conda-forge -c cdat --all
```

**Comment by victorquik** [comment]
Yes, that worked! Thanks

**Comment by jypeter** [comment]
@doutriaux1 @dnadeau4  for your information, I just had a similar problem when importing cdms2 of the **8.0** version on a brand new **Windows 10+WSL**.

No problem when importing cdms2 in the **nightly** version (as suggested just above).

And I was able to import cdms2 in 8.0 on a regular Linux server

```
jypeter@lsce4078:~$ python
Python 2.7.15 | packaged by conda-forge | (default, Feb 26 2019, 02:46:43) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cdms2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jypeter/miniconda3/envs/cdat-8.0_py2/lib/python2.7/site-packages/cdms2/__init__.py", line 33, in <module>
    from .dataset import createDataset, openDataset, useNetcdf3  # noqa
  File "/home/jypeter/miniconda3/envs/cdat-8.0_py2/lib/python2.7/site-packages/cdms2/dataset.py", line 7, in <module>
    from . import Cdunif
ImportError: libnetcdf.so.11: cannot open shared object file: No such file or directory

>>> import cdms2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jypeter/miniconda3/envs/cdat-8.0_py2/lib/python2.7/site-packages/cdms2/__init__.py", line 7, in <module>
    from . import git  # noqa
ImportError: cannot import name git
>>>


jypeter@lsce4078:~$ conda list | grep netcdf
libnetcdf                 4.6.1                         2    conda-forge
netcdf-fortran            4.4.4                         7    conda-forge
```
