### ISSUE TITLE
implement context management with the `with` keyword 

### ISSUE THREAD

**Issue by zshaheen** [CDAT/cdms#94]
I think cdms should support context management with the `with` keyword. So the idea is to have something similar to how files are handled in Python:

```python
with cdms2.open('precc.nc') as precc_file:
   var = precc_file('PRECC')
```

This automatically has exception handling and automatically closes the file after leaving the scope. All that is needed is to implement `__enter__()` and `__exit__()` functions.

**Comment by doutriaux1** [comment]
should be fixed by https://github.com/UV-CDAT/cdms/pull/121
